name: Mingle
version: '1.0-SNAPSHOT'
main: org.mateh.mingle.Main
api-version: '1.20'
commands:
  mingle:
    description: Main command to control the game.
  room:
    description: Command to manage rooms.